# Generated by Django 5.0.3 on 2024-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_api', '0002_event_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('theatre', 'Theatre'), ('comedy', 'Comedy'), ('education', 'Education')], default='music', max_length=50),
        ),
    ]
